In [118]:
# Libraries
import numpy as np
import random

### 1. Simulate any random rectangular matrix A.

To generate random matrix we going o use random numpy function. This is going to generate a matrix with a min shape (2,2) and a max shape (20,20). Is easy increase or decrease this parameters

In [134]:
m = np.random.randint(low=2, high=20)
n = np.random.randint(low=2, high=20)
m,n

(6, 6)

Now we generate the A matrix with shape n,p and float random values

In [135]:
randomlist = random.sample(range(0, m*n), m*n)
A = np.array(randomlist).reshape((m,n)).astype('float')
print(A)

[[13. 29. 27. 14. 20.  1.]
 [31. 24.  8. 15. 30.  4.]
 [33. 28. 10. 26. 16. 18.]
 [ 0. 17. 35.  5. 25.  7.]
 [21. 23.  6. 22. 32.  9.]
 [ 3.  2. 34. 12. 19. 11.]]


### What is the rank and trace of A?

To calculate the rank of A we going to use the function linalg.matrix_rank of numpy. This value means that there are n max num of columns (or rows) linearly independent

In [136]:
rank = np.linalg.matrix_rank(A)
print(f"Number of vectos linearly independent: {rank}")

Number of vectos linearly independent: 6


### What is the determinant of A?

We gonna to use the function linalg.det to calculated. This function use the LU factorization. For this case we need to check that m is equal to n because the determinat is denifed only fo square matrix

In [137]:
if A.shape[0] == A.shape[1]:
    determinant = np.linalg.det(A)
    print(f"The determinant of A is : {determinant}")
else:
    print(f"Matrix must be sqare")

The determinant of A is : -79296324.99999984


### Can you invert A? How?

We can inver the matrix A with the numpy function linalg.inv, but, we need to make sure of the folling condition:
- A is invertible is different from zero



In [138]:
if A.shape[0] == A.shape[1]:
    determinant = np.linalg.det(A)
    if determinant != 0:
        inverse = np.linalg.inv(A)
        print("The inverse of A is: ")
        print(inverse)
    else:
        print(f"Matrix is not invertible - determinant : {determinant}")
else:
    print(f"Matrix must be sqare")

The inverse of A is: 
[[-0.00831272  0.05866955  0.00943586 -0.01708394 -0.05104385  0.01661557]
 [ 0.01367921 -0.02351982  0.01831979  0.03811038  0.00471781 -0.05078083]
 [ 0.0186976   0.01145312 -0.00059937 -0.00787731 -0.03120567  0.02566099]
 [ 0.05680119 -0.0485689  -0.01578702 -0.08187255  0.05483268  0.04556859]
 [-0.02565058  0.01555551 -0.02352737  0.01994227  0.03020619 -0.00223004]
 [-0.07567199 -0.02100936  0.05380871  0.07694792 -0.00247464 -0.02956464]]


### How are eigenvalues and eigenvectors of A’A and AA’ related? What interesting differences can you notice between both?

We gonna to calculare eigenvalues and eigenvectors with numpy function linalg.eig

AT A

In [139]:
AtA = np.dot(A.T, A)
eigenvalues_ata, eigenvectors_ata = np.linalg.eig(AtA)

In [140]:
print(eigenvalues_ata)

[12113.71907608  2051.74563373    78.97428924    32.62197314
   360.66771671   272.27131111]


In [141]:
print(eigenvectors_ata)

[[ 0.40924565 -0.53558985 -0.71723067  0.02615685 -0.1729904   0.02513574]
 [ 0.47915019 -0.17865192  0.35114222  0.22706763  0.36078697  0.65838497]
 [ 0.40343323  0.79612342 -0.31056402 -0.10121057 -0.20401551  0.23476203]
 [ 0.36163756 -0.19074466  0.41901091 -0.69691294 -0.40740671 -0.07481129]
 [ 0.524577    0.1043739   0.08744606  0.09588592  0.46947174 -0.69042046]
 [ 0.18496475 -0.01170726  0.28742362  0.66530502 -0.64179498 -0.16884036]]


A AT

In [142]:
AAt = np.dot(A, A.T)
eigenvalues_aat, eigenvectors_aat = np.linalg.eig(AAt)

In [143]:
print(eigenvalues_aat)

[12113.71907608  2051.74563373   360.66771671   272.27131111
    32.62197314    78.97428924]


In [144]:
print(eigenvectors_aat)

[[ 0.41656098 -0.19332977 -0.30274326  0.6505137  -0.52200104  0.04235461]
 [ 0.44806804  0.31567166 -0.37227308 -0.24554197  0.09365287 -0.70138254]
 [ 0.47319381  0.40214399  0.64662079  0.33822504  0.2799395   0.05905147]
 [ 0.34964804 -0.58285046 -0.22115605  0.03592376  0.6806363   0.15673321]
 [ 0.44013588  0.25479895 -0.19615356 -0.49571328 -0.19458838  0.6475225 ]
 [ 0.29296118 -0.54462652  0.51405701 -0.39385621 -0.37315885 -0.24275678]]


For this values we can note that:
- The eigenvalues are the same but in different order
- The eigenvalues are the same but the eigenvector are different